"use client";

import { Footer } from "@/components/landing/footer";
import { Header } from "@/components/landing/header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { User, Calendar, Facebook, MessageCircle, Send } from "lucide-react";
import { notFound } from "next/navigation";

const blogPosts = [
  {
    id: 1,
    title: "Referral Income Doubled for Level 2!",
    slug: "referral-income-doubled-level-2",
    image: "/images/home/testimonial1.jpg",
    description:
      "Exciting news! We've permanently doubled the referral commission for Level 2 members. Learn how this impacts your earnings.",
    tags: ["Announcement", "Earnings Tips"],
    date: "2024-07-10",
    author: "UEIEP Team",
    content: `
      <p>We are thrilled to announce a significant enhancement to our referral program: the commission for Level 2 referrals has been permanently doubled! This change is effective immediately and is designed to reward our dedicated members even more for building robust downlines.</p>
      <h2>What Does This Mean for You?</h2>
      <p>Previously, Level 2 referrals earned you an 8% commission. With this update, you will now earn a generous <strong>16% commission</strong> on all earnings generated by your Level 2 downline members. This is a direct increase that will significantly boost your passive income.</p>
      <img src="/images/home/testimonial1.jpg" alt="Referral Commission Chart" class="my-6 rounded-lg shadow-md" />
      <h3>Why This Change?</h3>
      <p>Our goal at UEIEP is to empower our community members with the best possible earning opportunities. We've seen tremendous growth and engagement from our Level 2 network, and this increase is a direct reflection of our commitment to rewarding your efforts in expanding the UEIEP family.</p>
      <p>This adjustment also aims to incentivize deeper network building, ensuring that more members benefit from the multi-level referral system.</p>
      <h2>How to Maximize Your Earnings</h2>
      <ul><li><strong>Supporting Your Direct Referrals:</strong> Help your Level 1 members succeed, as their activity directly impacts your Level 2 earnings.</li><li><strong>Sharing the News:</strong> Inform your network about this exciting update to encourage them to build their own downlines.</li><li><strong>Utilizing Referral Tools:</strong> Use our pre-written messages, banners, and video creatives available in the 'Referral Toolkit' section of your dashboard.</li></ul>
      <p>We believe this change will create even more opportunities for financial growth and stability for all our members. Thank you for being a vital part of the UEIEP community!</p>
      <h3>Stay Tuned for More Updates!</h3>
      <p>We are continuously working on new features and improvements to enhance your experience and earning potential on the platform. Keep an eye on our blog for the latest announcements and tutorials.</p>
      <div class="my-6 p-4 bg-sky-500/10 border border-sky-500/30 rounded-lg"><p class="text-sky-300 font-semibold"><strong>Reminder:</strong> All earnings are subject to our Terms & Conditions. Please review them for full details.</p></div>
    `,
  },
  {
    id: 2,
    title: "Mastering Daily Assignments: A Step-by-Step Guide",
    slug: "mastering-daily-assignments",
    image: "/images/home/testimonial1.jpg",
    description:
      "Unlock your full earning potential with our comprehensive guide to completing daily assignments efficiently and effectively.",
    tags: ["Tutorial", "Earnings Tips"],
    date: "2024-07-05",
    author: "John Doe",
    content: `
      <p>Daily assignments are the backbone of your earnings on the UEIEP platform. By efficiently completing these tasks, you can significantly boost your daily income. This guide will walk you through the best practices to master your daily assignments.</p>
      <h2>Understanding Daily Assignments</h2>
      <p>Each day, you'll receive a set of video-watching assignments. These tasks are designed to help our partner channels gain engagement. Your role is to watch the video for a specified duration, like it, and subscribe to the channel.</p>
      <h3>Step-by-Step Completion</h3>
      <ol><li><strong>Access Assignments:</strong> Navigate to the 'Daily Assignments' section in your dashboard.</li><li><strong>Select a Video:</strong> Click on any pending assignment. A new tab will open with the Social media video.</li><li><strong>Watch Fully:</strong> Ensure you watch the video for the entire required duration (55 seconds for shorts, 10 minutes for long videos). Do not close the tab prematurely.</li><li><strong>Engage:</strong> Like the video and subscribe to the channel. This is crucial for verification.</li><li><strong>Verify:</strong> Once the timer on the UEIEP platform completes, the assignment will automatically be marked as 'Completed'.</li></ol>
      <div class="my-6 p-4 bg-green-500/10 border border-green-500/30 rounded-lg"><p class="text-green-300 font-semibold"><strong>Pro Tip:</strong> You can open multiple assignment tabs simultaneously, but ensure each video plays fully in its respective tab to register completion.</p></div>
      <h2>Tips for Efficiency</h2>
      <ul><li><strong>Dedicated Time Slot:</strong> Set aside a specific time each day to complete your assignments without distractions.</li><li><strong>Stable Internet:</strong> A stable internet connection ensures smooth video playback and accurate tracking.</li><li><strong>Browser Optimization:</strong> Close unnecessary tabs and applications to free up resources for better performance.</li><li><strong>Mobile App:</strong> Use our mobile-optimized platform for on-the-go assignment completion.</li></ul>
      <p>By following these steps and tips, you'll be able to complete your daily assignments quickly and maximize your earnings. Happy earning!</p>
      <h3>Watch Our Video Tutorial!</h3>
      <div class="my-6 aspect-video"><iframe width="100%" height="100%" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Social Media video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen class="rounded-lg shadow-md"></iframe></div>
    `,
  },
  {
    id: 3,
    title: "New AI Video Topics Released for July!",
    slug: "new-ai-video-topics-july",
    image: "/images/home/testimonial1.jpg",
    description:
      "Discover the latest trending topics our AI has identified for your next viral Social Media video. Get ready to create engaging content!",
    tags: ["System Updates", "AI Videos"],
    date: "2024-07-01",
    author: "UEIEP AI Lab",
    content: `<p>The UEIEP AI Lab is excited to announce the release of new, highly trending AI video topics for July! Our advanced algorithms have analyzed millions of data points to identify niches and keywords that are currently exploding on Social Media. This means more views, more engagement, and more earnings for your channel!</p><h2>Featured Topics for July</h2><ul><li><strong>Sustainable Living:</strong> "Eco-Friendly Home Hacks," "Zero Waste Lifestyle Tips," "Renewable Energy Explained"</li><li><strong>Future Tech:</strong> "Quantum Computing Breakthroughs," "AI in Healthcare," "Metaverse Beyond Gaming"</li><li><strong>Financial Freedom:</strong> "Passive Income Strategies 2024," "Investing for Beginners," "Cryptocurrency Trends"</li><li><strong>Personal Development:</strong> "Mindfulness for Productivity," "Building Healthy Habits," "Effective Time Management"</li></ul><img src="/images/home/testimonial1.jpg" alt="Trending Topics Graph" class="my-6 rounded-lg shadow-md" /><h3>How to Access New Videos</h3><p>Simply navigate to the 'AI Videos' section in your dashboard. Your personalized video recommendations based on these trending topics will be available for download. Remember to upload them to your Social Media and optimize with the provided titles and descriptions for maximum impact.</p><p>We are committed to providing you with the most relevant and high-performing content to ensure your success on Social Media. Happy creating!</p>`,
  },
  {
    id: 4,
    title: "Understanding Your Downline: Maximizing Passive Income",
    slug: "understanding-your-downline",
    image: "/images/home/testimonial1.jpg",
    description:
      "A deep dive into the 5-level referral system and strategies to grow your network for sustainable passive income.",
    tags: ["Tutorial", "Referral"],
    date: "2024-06-28",
    author: "Jane Smith",
    content: `<p>The UEIEP referral program is a powerful way to generate passive income. Understanding how your downline works and how to effectively grow it is key to maximizing your earnings. This guide will break down the 5-level system and offer strategies for success.</p><h2>The 5-Level Referral System Explained</h2><p>Our unique multi-level referral system allows you to earn commissions not just from your direct referrals (Level 1), but also from the earnings of those they refer, down to five levels deep. Each level offers a different commission percentage:</p><ul><li><strong>Level 1:</strong> 15%</li><li><strong>Level 2:</strong> 8%</li><li><strong>Level 3:</strong> 5%</li><li><strong>Level 4:</strong> 3%</li><li><strong>Level 5:</strong> 1%</li></ul><p>This structure means that by helping your direct referrals succeed, you indirectly benefit from the growth of their networks.</p><h3>Strategies for Downline Growth</h3><ol><li><strong>Educate Your Directs:</strong> Teach your Level 1 referrals how the system works and encourage them to be active.</li><li><strong>Share Success Stories:</strong> Use testimonials and your own earning proof to motivate potential referrals.</li><li><strong>Utilize Referral Tools:</strong> Leverage the pre-written messages, banners, and video creatives available in your 'Referral Toolkit'.</li><li><strong>Host Webinars/Workshops:</strong> Organize online sessions to explain the platform and referral benefits to a wider audience.</li><li><strong>Be a Mentor:</strong> Provide ongoing support and guidance to your downline members to ensure their continued activity and success.</li></ol><div class="my-6 p-4 bg-sky-500/10 border border-sky-500/30 rounded-lg"><p class="text-sky-300 font-semibold"><strong>Remember:</strong> A strong, active downline is the foundation of significant passive income. Invest time in nurturing your network!</p></div><p>By actively engaging with and supporting your downline, you create a ripple effect that can lead to substantial long-term earnings. Start building your network today!</p>`,
  },
  {
    id: 5,
    title: "Platform Security Enhancements: What You Need to Know",
    slug: "platform-security-enhancements",
    image: "/images/home/testimonial1.jpg",
    description:
      "We've rolled out significant security updates to protect your data and earnings. Learn about the new features.",
    tags: ["System Updates", "Security"],
    date: "2024-06-20",
    author: "UEIEP Security Team",
    content: `<p>At UEIEP, the security of your data and earnings is our top priority. We are continuously working to implement the latest security measures to protect our platform and its Admins. We're excited to announce several significant security enhancements that have recently been rolled out.</p><h2>New Security Features</h2><ul><li><strong>Enhanced Data Encryption:</strong> All sensitive Admin data is now encrypted with advanced AES-256 encryption.</li><li><strong>Multi-Factor Authentication (MFA) Options:</strong> We've introduced more flexible MFA options, including authenticator apps.</li><li><strong>Real-time Fraud Detection:</strong> Our new AI-powered system monitors for suspicious patterns to prevent fraud.</li><li><strong>Regular Security Audits:</strong> We've increased the frequency of our third-party security audits.</li></ul><img src="/images/home/testimonial1.jpg" alt="Security Lock Icon" class="my-6 rounded-lg shadow-md" /><h3>What You Can Do</h3><ul><li><strong>Use Strong Passwords:</strong> Create unique, complex passwords for your UEIEP account.</li><li><strong>Enable MFA:</strong> We highly recommend enabling multi-factor authentication for maximum protection.</li><li><strong>Be Vigilant:</strong> Be wary of phishing attempts. We will never ask for your password via email or SMS.</li><li><strong>Report Suspicious Activity:</strong> If you notice unusual activity, report it to support immediately.</li></ul><p>These enhancements are part of our ongoing commitment to providing a safe and secure environment for all our Admins. Thank you for trusting UEIEP.</p>`,
  },
];

export default function BlogPostPage({ params }: { params: { slug: string } }) {
  const post = blogPosts.find((p) => p.slug === params.slug);

  if (!post) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-gray-900 dark:text-white">
      <Header />
      <main>
        <section className="relative py-24 md:py-32">
          <div className="absolute inset-0">
            <img
              src={post.image}
              alt={post.title}
              className="w-full h-full object-cover opacity-10 dark:opacity-20"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-white dark:from-slate-950 via-white/80 dark:via-slate-950/80 to-transparent"></div>
          </div>
          <div className="container mx-auto px-4 relative z-10 text-center">
            <div className="flex flex-wrap gap-2 justify-center mb-4">
              {post.tags.map((tag) => (
                <Badge
                  key={tag}
                  variant="outline"
                  className="text-primary dark:text-teal-400 border-primary/50 dark:border-teal-400/50 bg-primary/10 dark:bg-teal-500/10"
                >
                  {tag}
                </Badge>
              ))}
            </div>
            <h1 className="text-3xl md:text-5xl font-extrabold mb-4 text-gray-900 dark:text-slate-100 max-w-4xl mx-auto">
              {post.title}
            </h1>
            <div className="flex items-center justify-center space-x-6 text-gray-600 dark:text-slate-400 text-sm">
              <span className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                <span>
                  {new Date(post.date).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                </span>
              </span>
              <span className="flex items-center gap-1.5">
                <User className="h-4 w-4" />
                <span>By {post.author}</span>
              </span>
            </div>
          </div>
        </section>

        <section className="py-16">
          <div className="container mx-auto px-4 max-w-4xl">
            <div
              className="prose prose-lg max-w-none 
              dark:prose-invert 
              prose-p:text-gray-700 dark:prose-p:text-slate-400 
              prose-headings:text-gray-900 dark:prose-headings:text-slate-100 
              prose-strong:text-gray-900 dark:prose-strong:text-slate-100 
              prose-ul:marker:text-primary dark:prose-ul:marker:text-teal-400 
              prose-ol:marker:text-primary dark:prose-ol:marker:text-teal-400 
              prose-a:text-primary hover:prose-a:text-primary/80 dark:prose-a:text-teal-400 dark:hover:prose-a:text-teal-300
            "
            >
              <div dangerouslySetInnerHTML={{ __html: post.content }} />
            </div>
            <div className="mt-12 pt-8 border-t border-gray-200 dark:border-slate-800 text-center">
              <span className="font-semibold text-gray-700 dark:text-slate-300 mb-4 block">
                Share this post
              </span>
              <div className="flex flex-wrap items-center justify-center gap-4">
                <Button
                  variant="outline"
                  className="border-gray-300 hover:bg-gray-100 dark:border-slate-700 dark:hover:bg-slate-800"
                >
                  <MessageCircle className="mr-2 h-4 w-4" />
                  WhatsApp
                </Button>
                <Button
                  variant="outline"
                  className="border-gray-300 hover:bg-gray-100 dark:border-slate-700 dark:hover:bg-slate-800"
                >
                  <Send className="mr-2 h-4 w-4" />
                  Telegram
                </Button>
                <Button
                  variant="outline"
                  className="border-gray-300 hover:bg-gray-100 dark:border-slate-700 dark:hover:bg-slate-800"
                >
                  <Facebook className="mr-2 h-4 w-4" />
                  Facebook
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
