"use client";

import { Footer } from "@/components/landing/footer";
import { Header } from "@/components/landing/header";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Input } from "@/components/ui/input";
import { AnimatePresence, motion } from "framer-motion";
import {
  Banknote,
  ChevronDown,
  Clapperboard,
  ClipboardList,
  HelpCircle,
  LifeBuoy,
  Mail,
  MessageCircle,
  Rocket,
  Search,
} from "lucide-react";
import { useMemo, useState } from "react";

const faqData = [
  {
    category: "Getting Started",
    icon: Rocket,
    faqs: [
      {
        q: "How do I join the UEIEP platform?",
        a: "To join, you need a referral link from an existing member. Use it to complete the registration, verify your details via OTP, and accept our terms. The process is quick and designed to get you started in minutes.",
      },
      {
        q: "What do I need to get started?",
        a: "You'll need a valid email and mobile number, a UPI ID for payments, a Social Media (which can be new), a referral ID, and a device with internet access.",
      },
      {
        q: "Is there any joining fee?",
        a: "No, joining UEIEP is completely free. We believe in providing opportunities without any upfront cost. You can start earning from day one.",
      },
      {
        q: "How long does account approval take?",
        a: "Account verification is instant after OTP confirmation. However, the initial review of your Social Media setup by our team might take take few minute to 48 hours to ensure everything is aligned for content distribution.",
      },
    ],
  },
  {
    category: "Earnings & Payments",
    icon: Banknote,
    faqs: [
      {
        q: "How much can I earn on UEIEP?",
        a: "Earnings depend on your engagement. Daily tasks offer a steady income, while revenue from your Social Media and referral commissions can significantly boost your total earnings. Top performers earn substantial monthly incomes.",
      },
      {
        q: "When and how do I get paid?",
        a: "Payments are processed directly to your UPI ID within 24-48 hours of a withdrawal request. The minimum withdrawal amount is ₹100, making it easy to access your earnings.",
      },
      {
        q: "What is the referral commission structure?",
        a: "Our multi-level referral system is a great way to build passive income. You earn a percentage of the earnings generated by the members you refer, extending through several levels.",
      },
      {
        q: "Are there any taxes on earnings?",
        a: "As an independent Admin, you are responsible for your own tax obligations based on your income. UEIEP provides detailed earning statements to help with your tax filing.",
      },
    ],
  },
  {
    category: "Daily Assignments",
    icon: ClipboardList,
    faqs: [
      {
        q: "What are daily assignments?",
        a: "Daily assignments involve simple social media engagement tasks, like watching and interacting with provided YouTube content. These tasks help our partners and provide you with a consistent daily income.",
      },
      {
        q: "How long do assignments take to complete?",
        a: "The time varies, but most Admins complete their daily assignments in a few hours, which can be done flexibly throughout the day to fit your schedule.",
      },
      {
        q: "What happens if I miss assignments?",
        a: "Missing occasional assignments is fine. However, consistent inactivity might affect the number of tasks you receive. We encourage regular participation to maximize your earning potential.",
      },
      {
        q: "Can I complete assignments on mobile?",
        a: "Absolutely. The UEIEP platform is fully responsive and designed to work seamlessly on smartphones, tablets, and desktops, allowing you to earn on the go.",
      },
    ],
  },
  {
    category: "AI Videos & YouTube",
    icon: Clapperboard,
    faqs: [
      {
        q: "How do AI videos work?",
        a: "Our advanced AI generates high-quality, engaging videos on trending topics. We provide these videos to you, complete with optimization, for you to upload to your Social Media.",
      },
      {
        q: "How often do I get new AI videos?",
        a: "Active and consistent Admins typically receive several new AI-generated videos each week. The more engaged you are, the more content you'll get to grow your channel.",
      },
      {
        q: "What if my Social Media gets suspended?",
        a: "This is a rare occurrence as our content adheres to guidelines. If any issue arises, our support team will provide immediate assistance and guidance to resolve it.",
      },
      {
        q: "Can I edit the AI videos?",
        a: "Minor edits like adding a personal intro or outro are permitted. However, significant alterations to the core content are discouraged as they might conflict with our partnership agreements.",
      },
    ],
  },
  {
    category: "Support & Security",
    icon: LifeBuoy,
    faqs: [
      {
        q: "I'm having trouble logging in. What should I do?",
        a: "First, try the 'Forgot Password' link. If that doesn't work, clear your browser's cache or try a different browser. For persistent issues, contact our support team at support@ueiep.com.",
      },
      {
        q: "How do I keep my account secure?",
        a: "Use a strong, unique password and never share it. Be cautious of phishing attempts. Our platform uses OTP verification for critical actions to add an extra layer of security.",
      },
      {
        q: "How can I contact support?",
        a: "You can reach our support team 24/7 via live chat on the platform, by emailing support@ueiep.com, or by requesting a call back through the help section in your dashboard.",
      },
      {
        q: "Can I delete my account?",
        a: "Yes, you can request account deletion by contacting support. Please note that this action is permanent and will result in the loss of all data, earnings, and referrals.",
      },
    ],
  },
];

export default function FAQPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [activeCategory, setActiveCategory] = useState(faqData[0].category);

  const filteredData = useMemo(() => {
    if (!searchTerm) {
      return faqData.find((cat) => cat.category === activeCategory);
    }
    const results = faqData
      .map((category) => ({
        ...category,
        faqs: category.faqs.filter(
          (faq) =>
            faq.q.toLowerCase().includes(searchTerm.toLowerCase()) ||
            faq.a.toLowerCase().includes(searchTerm.toLowerCase())
        ),
      }))
      .filter((category) => category.faqs.length > 0);
    return { category: "Search Results", faqs: results.flatMap((r) => r.faqs) };
  }, [searchTerm, activeCategory]);

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-gray-900 dark:text-white font-sans">
      <Header />
      <main>
        <section className="py-20 md:py-28 relative text-center overflow-hidden">
          <div className="absolute -top-1/4 -left-1/4 w-1/2 h-1/2 bg-primary/5 dark:bg-teal-500/10 rounded-full filter blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-1/4 -right-1/4 w-1/2 h-1/2 bg-sky-500/5 dark:bg-sky-500/10 rounded-full filter blur-3xl animate-pulse animation-delay-4000"></div>

          <div className="container mx-auto px-4 relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
            >
              <h1 className="text-4xl md:text-6xl font-extrabold mb-4 bg-gradient-to-br from-gray-900 to-gray-600 dark:from-white dark:to-slate-400 bg-clip-text text-transparent">
                How can we help?
              </h1>
              <p className="text-lg md:text-xl text-gray-600 dark:text-slate-400 mb-8 max-w-3xl mx-auto">
                Find answers, tutorials, and deep-dives into our platform's
                features.
              </p>
              <div className="max-w-2xl mx-auto">
                <div className="relative">
                  <Search className="absolute left-5 top-1/2 transform -translate-y-1/2 text-gray-400 dark:text-slate-500 h-5 w-5" />
                  <Input
                    placeholder="Search for answers..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="h-14 pl-14 pr-4 w-full text-lg bg-white/80 dark:bg-slate-900/80 border-gray-300 dark:border-slate-700 rounded-full focus:ring-2 focus:ring-primary dark:focus:ring-teal-500 focus:border-primary dark:focus:border-teal-500 transition-all placeholder-gray-500 dark:placeholder-slate-500"
                  />
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        <section className="py-16">
          <div className="container mx-auto px-4 max-w-7xl">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              <aside className="md:col-span-1">
                <h2 className="text-lg font-semibold text-gray-800 dark:text-slate-300 mb-4 px-3">
                  Categories
                </h2>
                <nav className="space-y-1">
                  {faqData.map((cat) => (
                    <button
                      key={cat.category}
                      onClick={() => {
                        setActiveCategory(cat.category);
                        setSearchTerm("");
                      }}
                      className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-left transition-colors text-base font-medium ${
                        activeCategory === cat.category && !searchTerm
                          ? "bg-primary/10 text-primary dark:bg-teal-500/10 dark:text-teal-300"
                          : "text-gray-600 dark:text-slate-400 hover:bg-gray-100 dark:hover:bg-slate-800/50 hover:text-gray-800 dark:hover:text-slate-200"
                      }`}
                    >
                      <cat.icon className="h-5 w-5 flex-shrink-0" />
                      <span>{cat.category}</span>
                    </button>
                  ))}
                </nav>
              </aside>

              <div className="md:col-span-3">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={searchTerm || activeCategory}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                  >
                    {!filteredData || filteredData.faqs.length === 0 ? (
                      <div className="text-center py-20">
                        <HelpCircle className="h-16 w-16 text-gray-300 dark:text-slate-700 mx-auto mb-4" />
                        <h3 className="text-xl font-semibold text-gray-800 dark:text-slate-300 mb-2">
                          No Results Found
                        </h3>
                        <p className="text-gray-500 dark:text-slate-500">
                          Your search for "{searchTerm}" didn't yield any
                          results.
                        </p>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        <h2 className="text-3xl font-bold text-gray-900 dark:text-slate-100 mb-6">
                          {filteredData.category}
                        </h2>
                        {filteredData.faqs.map((faq, index) => (
                          <Collapsible
                            key={index}
                            className="border-b border-gray-200 dark:border-slate-800 last:border-b-0"
                          >
                            <CollapsibleTrigger className="w-full text-left py-5 flex justify-between items-center group">
                              <h3 className="font-semibold text-gray-800 dark:text-slate-200 text-lg group-hover:text-primary dark:group-hover:text-teal-400 transition-colors pr-4">
                                {faq.q}
                              </h3>
                              <ChevronDown className="h-6 w-6 text-gray-500 dark:text-slate-500 transition-transform duration-300 group-data-[state=open]:rotate-180 flex-shrink-0" />
                            </CollapsibleTrigger>
                            <CollapsibleContent>
                              <div className="pb-5 pr-8">
                                <p className="text-gray-600 dark:text-slate-400 leading-relaxed max-w-prose">
                                  {faq.a}
                                </p>
                              </div>
                            </CollapsibleContent>
                          </Collapsible>
                        ))}
                      </div>
                    )}
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </div>
        </section>

        <section className="py-20">
          <div className="container mx-auto px-4 max-w-6xl">
            <div className="rounded-2xl p-8 md:p-12 text-center relative overflow-hidden bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-800">
              <div className="absolute inset-0 bg-gradient-to-br from-primary/5 dark:from-teal-500/5 via-transparent to-transparent"></div>
              <div className="relative z-10">
                <h2 className="text-3xl font-bold mb-4 text-gray-900 dark:text-white">
                  Still have questions?
                </h2>
                <p className="text-gray-600 dark:text-slate-400 mb-8 max-w-2xl mx-auto">
                  Our support team is ready to assist you. Reach out and we'll
                  get back to you as soon as possible.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Button
                    size="lg"
                    className="bg-primary hover:bg-primary-hover text-primary-foreground dark:bg-teal-600 dark:hover:bg-teal-700 dark:text-white font-bold shadow-lg transform hover:scale-105 transition-transform"
                  >
                    <MessageCircle className="mr-2 h-5 w-5" />
                    Chat With Us
                  </Button>
                  <Button
                    size="lg"
                    variant="outline"
                    className="border-gray-300 text-gray-700 hover:bg-gray-100 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700 dark:hover:bg-slate-700 dark:hover:border-slate-600 font-semibold"
                  >
                    <Mail className="mr-2 h-5 w-5" />
                    Email Support
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
